---
title: "Applied Data Mining Homework 05"
author: "Xun Zhao, xz2827"
output: pdf_document
fontsize: 12pt
---

# Problem 1

```{r, results = 'hide'}
w1 = c(1, 1)
w2 = c(1, 1 / 2)
w3 = c(1, -1)
w4 = c(1, -1 / 2)
X = as.matrix(seq(-10, 10, length.out = 101))
sigmoid = function(x) as.matrix(1 / (1 + exp(-x)))
max0 = function(x) as.matrix(ifelse(x > 0, x, 0))
f = function(X, W, phi){
	Z = phi(X %*% W)
	Y_ = sigmoid(Z %*% as.matrix(c(1, 1)))}
Ws = rbind(w1, w2, w3, w4)
par(mfrow = c(2, 2))
apply(Ws, 1, FUN = function(w)plot(X, f(X, t(w), sigmoid), type = 'l'))
par(mfrow = c(2, 2))
apply(Ws, 1, FUN = function(w)plot(X, f(X, t(w), max0), type = 'l'))
```

# Problem 2

```{r, results = 'hide'}
cnt = 31
seq = seq(-10, 10, length.out = cnt)
X = cbind(rep(seq, each = cnt), rep(seq, cnt))
sigmoid = function(x) 1 / (1 + exp(-x))
max0 = function(x) ifelse(x > 0, x, 0)
f = function(X, W, phi){
	Z = phi(X %*% W)
	OUT = sigmoid(Z %*% matrix(rep(1, dim(W)[2]), c(dim(W)[2], 1)))
	matrix(OUT, c(cnt, cnt))}

sapply(1:8, function(i){
	ws = rnorm(6, 0, 1)
	par(mfrow = c(1, 3), pin = c(2, 3.5))
	sapply(1:3, function(j){
		fun = ifelse(i < 4, sigmoid, max0)
		persp(x = seq, y = seq, f(X, matrix(ws[1:(2 * j)], c(2, j)), fun),
		xlab = 'x', ylab = 'y', zlab = 'z',
		main = paste(c('#HidenNodes: ', j, 
		'\nFunc: ', ifelse(i < 4, 'sigmoid', 'max0')), collapse = ''),
		theta = 45, phi = 15, col = 'lightblue')
	})	
})
```